import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./bootstrapClient";

export const metadata = {
  title: 'SocialHub',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body data-bs-theme="dark">
        {children}
        <BootstrapClient />
      </body>
    </html>
  )
}
